# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('processing', 'Обработка'), ('ready', 'Готово'), ('published', 'Опубликовано')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.project')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edit_type', models.CharField(choices=[('cut', 'Обрезка'), ('audio_overlay', 'Наложение звука'), ('text_overlay', 'Текст на экране'), ('image_overlay', 'Вставка изображения'), ('fade', 'Затемнение/Потухание'), ('volume', 'Регулировка громкости')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='video_editor.video')),
            ],
            options={
                'db_table': 'video_edits',
            },
        ),
        migrations.CreateModel(
            name='VideoTextTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('start_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('position', models.CharField(choices=[('top', 'Верх'), ('center', 'Центр'), ('bottom', 'Низ')], default='bottom', max_length=50)),
                ('style', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_tracks', to='video_editor.video')),
            ],
            options={
                'db_table': 'video_text_tracks',
            },
        ),
        migrations.CreateModel(
            name='VideoAudioTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file_path', models.CharField(max_length=500)),
                ('start_time', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('fade_in', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fade_out', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='video_editor.video')),
            ],
            options={
                'db_table': 'video_audio_tracks',
            },
        ),
        migrations.CreateModel(
            name='YouTubeUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('scheduled', 'Запланировано'), ('uploading', 'Загружается'), ('uploaded', 'Загружено'), ('failed', 'Ошибка')], default='pending', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_uploads', to='video_editor.video')),
            ],
            options={
                'db_table': 'youtube_uploads',
            },
        ),
    ]

