# Generated by Django 4.2.7 on 2025-12-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_videotemplate_options'),
        ('video_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videoaudiotrack',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='videoedit',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='videotexttrack',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='youtubeupload',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AddField(
            model_name='video',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.videotemplate'),
        ),
    ]
