# Generated by Django 4.2.7 on 2025-12-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotemplate',
            options={'ordering': ['name']},
        ),
    ]
